nodeLinker: node-modules
packageExtensions:
  "@nextui-org/system@2.4.5":
    dependencies:
      "@nextui-org/theme": "^2.4.3"
      "tailwindcss": "^3.4.16"
  "@nextui-org/aria-utils@2.2.6":
    dependencies:
      "framer-motion": "^11.15.0"
