import { HeroUIProvider } from "@heroui/system";
import type { Metadata } from "next";
import NavBar from "@/features/navbar";
import NextThemesProvider from "@/providers/next-themes-provider";
import { fetchUserEmail } from "./actions";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const email = await fetchUserEmail();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <HeroUIProvider>
          <NextThemesProvider>
            <NavBar email={email} />
            {children}
          </NextThemesProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
