import { HeroUIProvider } from "@heroui/system";
import type { Metadata } from "next";
import NavBar from "@/features/navbar";
import NextThemesProvider from "@/providers/next-themes-provider";
import { fetchUserEmail } from "./actions";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const email = await fetchUserEmail();
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <HeroUIProvider className="grid h-screen w-screen grid-rows-[auto,1fr]">
          <NextThemesProvider>
            <NavBar email={email} />
            <main className="size-full max-w-7xl justify-self-center overflow-y-auto overflow-x-hidden px-6 pb-8 pt-2">
              {children}
            </main>
          </NextThemesProvider>
        </HeroUIProvider>
      </body>
    </html>
  );
}
