"""edit newsletters table

Revision ID: 4452c64b2c78
Revises: 35ac198c3c80
Create Date: 2025-01-05 18:01:25.699582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4452c64b2c78'
down_revision: Union[str, None] = '35ac198c3c80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('name', sa.String(length=256), nullable=False))
    op.add_column('newsletters', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('newsletters', sa.Column('custom_prompt', sa.Text(), nullable=True))
    op.add_column('newsletters', sa.Column('send_frequency', sa.String(length=256), nullable=False))
    op.add_column('newsletters', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.drop_column('newsletters', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('newsletters', sa.Column('email', mysql.VARCHAR(length=64), nullable=False))
    op.drop_column('newsletters', 'is_active')
    op.drop_column('newsletters', 'send_frequency')
    op.drop_column('newsletters', 'custom_prompt')
    op.drop_column('newsletters', 'description')
    op.drop_column('newsletters', 'name')
    # ### end Alembic commands ###
