"""new base class

Revision ID: 87eec36ad8cc
Revises: 086b24dcfc46
Create Date: 2025-01-07 16:26:17.040566

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '87eec36ad8cc'
down_revision: Union[str, None] = '086b24dcfc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'name')
    op.drop_index('unique_topic_name', table_name='topics')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_topic_name', 'topics', ['name'], unique=True)
    op.add_column('sources', sa.Column('name', mysql.VARCHAR(length=256), nullable=False))
    # ### end Alembic commands ###
